package:
    name: nrel-rev
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

build:
  number: 0

source:
    git_url: ../

requirements:
  build:
    - python
    - pip
  run:
    - python
    - click
    - h5py
    - nrel-pysam>=2.1.4
    - nrel-rex>=0.1.10
    - numpy
    - pandas
    - packaging
    - plotting
    - plotly
    - psutil
    - scipy


about:
  home: "https://github.com/NREL/reV"
  license: BSD 3-Clause
  summary: "The Renewable Energy Potential (reV) Model"
  doc_url: "https://nrel.github.io/reV"
  dev_url: "https://github.com/NREL/reV"
